title: "Classical Music"
description: "Favorite classical recordings by composer"
theme: "just-the-docs"

url: "https://luhoo.github.io"   # your GitHub Pages root URL
baseurl: "/classical_music"      # the repository name

# Enable navigation
nav_sort: case_insensitive
