title: "Classical Music"
description: "Favorite classical recordings by composer"
remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"

url: https://LuHoo.github.io/classical_music

# Enable navigation
nav_sort: case_insensitive


baseurl: "/classical_music"
