"""Stable rule IDs from docs/architecture/validation-rules.md."""

RULE_SCH_YAML_SYNTAX = "SCH-001"
RULE_SCH_DUPLICATE_KEYS = "SCH-002"
RULE_SCH_REQUIRED_FIELDS = "SCH-003"
RULE_SCH_EMPTY_OPTIONAL = "SCH-004"
RULE_SCH_UNKNOWN_FIELDS = "SCH-005"
RULE_SCH_ABSOLUTE_URL = "SCH-006"
RULE_SCH_GRM_ISSUE = "SCH-007"
RULE_SCH_KEEP_LOOKING_BOOL = "SCH-008"

RULE_IDN_UNIQUE_ID = "IDN-001"
RULE_IDN_SLUG = "IDN-002"

RULE_REF_WG_COMPOSER = "REF-001"
RULE_REF_WORK_COMPOSER = "REF-002"
RULE_REF_WORK_GROUP = "REF-003"
RULE_REF_PERF_WORK = "REF-004"
RULE_REF_PERF_NOT_WORK_GROUP = "REF-005"
RULE_REF_WORK_RELATIONSHIP_WORK = "REF-006"
RULE_REF_PERFORMER_PERSON = "REF-007"

RULE_DOM_WORK_GROUP_NON_PERFORMABLE = "DOM-001"
RULE_DOM_WORK_GROUP_NO_DIRECT_PERFORMANCES = "DOM-002"
RULE_DOM_WORK_GROUP_NO_RECOMMENDATION = "DOM-003"
RULE_DOM_WORK_SINGLE_GROUP = "DOM-020"
RULE_DOM_WORK_NOT_MULTI_GROUP = "DOM-021"
RULE_DOM_PERF_SINGLE_WORK_ID = "DOM-041"
RULE_DOM_PERF_NO_MULTI_WORK = "DOM-042"
RULE_DOM_PERFORMER_REQUIRED = "DOM-044"

RULE_REC_PROFILE_ON_PERFORMANCE = "REC-006"
RULE_REC_NO_RECOMMENDED_TRUE = "REC-002"

RULE_REC_GEM_ONLY_WORK = "REC-020"
RULE_REC_GEM_NOT_WG_OR_PERF = "REC-021"

RULE_CAN_CANDIDATE_NOT_CANONICAL = "CAN-001"
RULE_CAN_WORKFLOW_NOT_CANONICAL = "CAN-002"

RULE_EXT_TIDAL_ON_PERFORMANCE = "EXT-002"

RULE_DUP_WORK_GROUP = "DUP-002"
RULE_DUP_WORK = "DUP-003"
RULE_DUP_PERFORMANCE = "DUP-004"
RULE_DUP_NEVER_AUTO_MERGE = "DUP-005"
